### ISSUE TITLE
Carbon error when running with a config file

### ISSUE THREAD

**Issue by buzkall** [tighten/lambo#189] opened 2023-08-07 12:19 UTC
In a brand new mac M2, with valet and php 8.2 and running Lambo v3.0.3 I can perform a successful lambo new project if I have no config file for lambo.

The minute I run
lambo edit-config
even if I don't change anything from the config file, I get this error when running lambo new project

```
➜  test lambo new test


      __                    __               v3.0.3
     / /   ____ _____ ___  / /_  ____
    / /   / __ `/ __ `__ \/ __ \/ __ \
   / /___/ /_/ / / / / / / /_/ / /_/ /
  /_____/\__,_/_/ /_/ /_/_.___/\____/

 Lambo: Super-powered 'laravel new' for Laravel and Valet.

In Creator.php line 928:

  Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in phar:///Users/buzkall/.composer/vendor/tightenco/la
  mbo/builds/lambo/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98
```

I've run composer global install and I'm don't know where else to look

**Comment by mattstauffer** [comment] 2023-08-08 02:24
Thanks for the issue report! Could you try out v3.1.1?

**Comment by buzkall** [comment] 2023-08-08 07:34
The v3.1.1 works! 😃

However, there seems to be an issue with the configuration after the browser item, because I've set link, secure and create_database to true, but nothing happens: the browser opens but no valet or db.

If I call the lambo command with --link --secure --create-db it works

**Comment by jonsugar** [comment] 2023-08-08 11:07
> The v3.1.1 works! 😃
> 
> However, there seems to be an issue with the configuration after the browser item, because I've set link, secure and create_database to true, but nothing happens: the browser opens but no valet or db.
> 
> If I call the lambo command with --link --secure --create-db it works

Duplicate of #183

**Comment by mattstauffer** [comment] 2023-08-09 00:57
Thanks for the review, and thanks for noting the duplicate @jonsugar! Closing as those are represented in the other issue.

**Closed by mattstauffer** 2023-08-09 00:57 UTC
Labels: duplicate
