### ISSUE TITLE
Lambo option "--secure" does not update "APP_URL" in .env to "https://"

### ISSUE THREAD

**Issue by camya** [tighten/lambo#184] opened 2022-09-14 19:20 UTC
This is about the `lambo --secure` option. 

The `APP_URL` in the `.env` file could be updated to the **https://** protocol, if the lambo **option** `--secure` or the **config** value `SECURE=true` is set.

At the moment, the APP_URL starts with **http://** every time.

**Comment by jonsugar** [comment] 2022-09-15 07:57
Hi @camya

I've marked this as a duplicate of #183 because I can only reproduce this bug when I set `SECURE=true` in `~/.lambo/config`. When I pass --secure on the command line it works as expected.

So, from my testing, this looks like the same bug as #183-That boolean flags in `~/.lambo/config` do not get applied.

**Comment by jonsugar** [comment] 2022-09-15 08:03
Duplicate of #183

**Closed** 2022-09-15 08:05 UTC
Labels: bug, duplicate
